services:
  - type: web
    name: membership-manager
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: "./00-laravel-deploy.sh"
    startCommand: ""
    plan: free
    healthCheckPath: "/"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
